import osmnx as ox
import networkx as nx
import matplotlib.pyplot as plt
import os
from sys import argv

# Configure OSMnx
ox.settings.use_cache = True
ox.settings.log_console = True
ox.settings.timeout = 1800
ox.settings.overpass_endpoint = "https://overpass.kumi.systems/api/interpreter" 
#MODIFY OSM SERVER ENDPOINT HERE!

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
RAW_DATA_DIR = os.path.join(BASE_DIR, '../data/raw')

def extract_jakarta_network(area_size = 'large'):
    """
    Extract road network from Jakarta
    area_size: 'small' (Central Jakarta) or 'large' (Greater Jakarta)
    """
    print("\n\tExtracting Jakarta road network from OpenStreetMap...")
    
    if area_size == 'small':
        place_name = "Central Jakarta, Jakarta, Indonesia"
        print(f"\tFetching: {place_name}\n")
    else:
        place_name = "Jakarta, Indonesia"
        print(f"\tFetching: {place_name}\n")
    
    
    os.makedirs(RAW_DATA_DIR, exist_ok=True)
    filename = f'jakarta_network_{area_size}.graphml'
    full_path = os.path.join(RAW_DATA_DIR, filename)

    if os.path.exists(full_path):
        print(f"\tFound existing data file!")
        print(f"\tPath: {full_path}")
        print("\tLoading from local disk...\n")
        
        try:
            G = ox.load_graphml(full_path)
            print("\n\tLoaded successfully!")
            return G
        except Exception as e:
            print(f"\nFile existed but was corrupt. Re-downloading... ({e})")

    try:
        G = ox.graph_from_place(place_name, network_type='drive')
        print(f"\n\tNetwork extracted successfully!")
        print(f"\tNodes (Intersections): {len(G.nodes())}")
        print(f"\tEdges (Road segments): {len(G.edges())}\n")
        
        #Save the road network
        ox.save_graphml(G, full_path)
        print(f"\n\tSaved to: {full_path}")
        return G
    
    except Exception as e:
        print(f"\n\tError: {e}")
        print("\tTry again or try using another server endpoint by modifying the code!\n")
        return None

def visualize_network(G, area_size):
    #Visualize the extracted network
    titles = {
        'small': "Road Network: Central Jakarta",
        'large': "Road Network: Greater Jakarta"
    }
    print("\n\tCreating visualization...\n")
    
    fig, ax = ox.plot_graph(G, node_size = 0, edge_linewidth = 0.5, figsize = (12, 12), show = False, close = False)
    
    os.makedirs(RAW_DATA_DIR, exist_ok=True)
    filename = f'network_map_{area_size}.png'
    full_path = os.path.join(RAW_DATA_DIR, filename)

    plot_title = titles.get(area_size, "Road Network: Jakarta")
    ax.set_title(plot_title, fontsize = 20, pad = 15, color = 'white')
    ax.text(0.95, 0.02, "Generated by GreenMap AI for BINUS AOL\nData: OpenStreetMap", 
            transform=ax.transAxes, 
            horizontalalignment='right', 
            fontsize=9, 
            color='#555555')
    
    fig.savefig(full_path, dpi=300, bbox_inches='tight')
    print(f"\n\tMap saved to: {full_path}")
    plt.close()

def get_network_stats(G):
    #Display network statistics
    print("\n\tNetwork Statistics:")
    print(f"\tTotal nodes: {len(G.nodes())}")
    print(f"\tTotal edges: {len(G.edges())}")
    
    # Road types distribution
    road_types = {}
    for u, v, data in G.edges(data=True):
        highway = data.get('highway', 'unknown')
        if isinstance(highway, list):
            highway = highway[0]
        road_types[highway] = road_types.get(highway, 0) + 1
    
    print(f"\n\tRoad types:")
    for road_type, count in sorted(road_types.items(), key=lambda x: x[1], reverse=True):
        print(f"\t{road_type}: {count}")

if __name__ == "__main__":
    selected_mode = None
    if len(argv) > 1:
        if argv[1] in ['1', '2']:
            selected_mode = argv[1]
        else:
            print(f"Argument '{argv[1]}' invalid. Ignoring.")
    else:
        print("\n\n\t" + "=" * 30)
        print("\tJAKARTA ROAD NETWORK EXTRACTOR")
        print("\t" + "=" * 30 + "\n")
        print("\tMode 1: Simple (Central Jakarta)")
        print("\tMode 2: Complete (Greater Jakarta)")
        while selected_mode not in ['1', '2']:
            selected_mode = input("\n\tChoose mode (1/2): ")

    size_key = 'small' if selected_mode == '1' else 'large'

    G = extract_jakarta_network(area_size=size_key)

    if G:
        get_network_stats(G)
        visualize_network(G, size_key)
        print("\n\t" + "=" * 16)
        print("\tSTEP 1 COMPLETE!")
        print("\t"+ "=" * 16)
        print("\n\tNext: Run 'python add_pollution_weights.py'")
